add cli template

diff --git a/.github/workflows/create-release-pr.yml b/.github/workflows/create-release-pr.yml
--- a/.github/workflows/create-release-pr.yml
+++ b/.github/workflows/create-release-pr.yml
@@ -1,4 +1,4 @@
-name: Create Pull Request to Verify AI Summary of Release Notes
+name: Create Pull Request to Add Release Info
 
 on:
   repository_dispatch:
@@ -85,6 +85,12 @@ jobs:
             git push
           fi
 
+      - name: Setup Matrix CLI
+        working-directory: apps/matrix-cli
+        run: |
+          pip install uv
+          uv sync
+
       - name: Authenticate with Google Cloud
         uses: 'google-github-actions/auth@v2'
         with:
@@ -111,7 +117,57 @@ jobs:
           git add "${FILENAME}" && \
           git commit -m "added release info json" && \
           git push
+      
+      - name: Discover Latest Official Release on GitHub
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          latest_official_release=$(gh release list --jq '.[0].tagName' --json tagName --order desc)
+          echo "latest_official_release=${latest_official_release}" >> "$GITHUB_ENV"
+  
+      - name: Detect bump type
+        working-directory: docs
+        run: |
+          pip install uv
+          uv venv -p 3.11
+          uv pip compile --quiet requirements.in --output-file requirements.txt
+          uv pip install -r requirements.txt 
+          uv run scripts/bump_detection.py "${{env.latest_official_release}}" "${{env.release}}" 
+
+      - name: Create Release Article Template
+        working-directory: apps/matrix-cli
+        env:
+          GH_TOKEN: ${{ github.token }}
+          POSTS_DIR: docs/src/releases/posts
+        # only create release notes for minor, major, and intermediate bumps
+        if: env.generate_article == 'True'
+        run: |
+          set -eux
+
+          TARGET_DIR="${GITHUB_WORKSPACE}/${POSTS_DIR}/${{ env.release }}"
+          FILE_PATH="${TARGET_DIR}/post.md"
+
+          if git ls-files --error-unmatch "$FILE_PATH" &> /dev/null; then
+            echo "File '$FILE_PATH' is already committed to the repository. Skipping release notes creation."
+            exit 0
+          fi
+
+          mkdir -p "${{env.release}}"
+
+          # If these fail, you may have crossed the quotas. See 
+          # https://cloud.google.com/vertex-ai/generative-ai/docs/quotas
+          uv run matrix releases article \
+            --headless \
+            --output-file "${{env.release}}/post.md" \
+            --no-disable-rendering \
+            --until ${{env.gitref}}
           
+          mv "${{env.release}}" "${GITHUB_WORKSPACE}/${POSTS_DIR}"
+          git add "$TARGET_DIR" && \
+          git commit -m "added release article template" && \
+          git push
+          
+            
       - name: Setup docs venv & generate yaml
         working-directory: docs/scripts
         run: |
@@ -144,7 +200,7 @@ jobs:
           This pull request was created because a release pipeline completed successfully. If this is a patch release (the release version does not end in 0, e.g. "v1.2.5") that was triggered as part of its weekly schedule, you may close this PR directly, unless you want it to [be logged on the website](https://docs.dev.everycure.org/releases/release_history/). A git tag was [created](https://github.com/everycure-org/matrix/tags) regardless, so people can check it out.
 
           Note: 
-          - for minor and major releases, release article should be written and added, meant as a kickstarter for the final release.
+          - for minor and major releases, release article should be written and added, meant as a kickstarter for the final release. Please refer to the [template](https://github.com/everycure-org/matrix/blob/main/.github/release.yml).
           - release information file is used for updating the release history page
           EOM
           )" \
